### ISSUE TITLE
Item Issue

### ISSUE THREAD

**Issue by jrodr10** [NoahBPeterson/SpawnerTiers#1]
Mob Spawner is invalid, when using /spawner tier ETC, it gives an invalid spawner and an extra mob egg. Mob Spawner cannot be placed as its invalid

**Comment by NoahBPeterson** [comment]
I was adding the spawner to the player's inventory as an Item rather than a BlockItem. I fixed this, but then went further and eliminated the need for the player to use spawn eggs or tier upgrading items on the spawner. As soon as the new resource is published it should work.
